<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0ILleVl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0ILleVl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0ILleVl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0ILleVl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0ILleVl\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '0ILleVl',
    'container.build_id' => 'f66382b3',
    'container.build_time' => 1652432314,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0ILleVl');
